### PR TITLE
bundle product options name is added

### PR DESCRIPTION
**Pull request by sandy6666**
https://github.com/scandipwa/scandipwa/issues/3022

### CODE REVIEW

**Comment by sandy6666** [comment]
@zans-laksa please review

**Review by zans-laksa — APPROVED** [review]
Code review passed.

**Comment by sandy6666** [comment]
@zans-laksa when this PR will be Merged?

**Comment by zans-laksa** [comment]
Please ask @carinadues

**Comment by sandy6666** [comment]
@carinadues when this PR will be Merged?

**Pull request merged**
