### PR TITLE
Stock, attribute, image resolving optimization

### PR DESCRIPTION
**Pull request by alfredsgenkins**
Following fields received massive rework:
```graphql
interface ProductInterface {
    attributes: [AttributeWithValue]
    image: OptimizedProductImage @resolver(class: "ScandiPWA\\CatalogGraphQl\\Model\\Resolver\\Value")
    small_image: OptimizedProductImage @resolver(class: "ScandiPWA\\CatalogGraphQl\\Model\\Resolver\\Value")
    thumbnail: OptimizedProductImage @resolver(class: "ScandiPWA\\CatalogGraphQl\\Model\\Resolver\\Value")
    only_x_left_in_stock: Float @resolver(class: "ScandiPWA\\CatalogGraphQl\\Model\\Resolver\\Value")
    stock_status: ProductStockStatus @resolver(class: "ScandiPWA\\CatalogGraphQl\\Model\\Resolver\\Value")
}
```

Their resovler `ScandiPWA\CatalogGraphQl\Model\Resolver\Value` is a pure value resolver, it takes requested field from value context. This allows to resolve field in parent resolver. The Value resolver declaration was necessary to prevent old resolver of those fields to fire.

Following collection loading helpers received a "post loading" bulk data gathering update:
- `Magento\ConfigurableProductGraphQl\Model\Resolver\ConfigurableVariant` -> `ScandiPWA\CatalogGraphQl\Model\Resolver\ConfigurableVariant`
- `Magento\CatalogGraphQl\Model\Resolver\Products\Query\Filter` -> `ScandiPWA\CatalogGraphQl\Model\Resolver\Products\Query\Filter`

**Important note: the Search collection was not altered. It can be relatively easily achieved, but not done here. Main focus was on PLP loading, not search. As it already works quick with Elastic.**

Following PR are dependent on this PR:
- `quote-graphql` - https://github.com/scandipwa/quote-graphql/pull/15 (Cart resolver is now resolving items products using this efficent strategy).
- `reviews-graphql` - https://github.com/scandipwa/reviews-graphql/pull/4 (If no review data present return valid value)
- `base-theme` - https://github.com/scandipwa/base-theme/pull/340 (made missing image load data correctly)

**PS 2**: TODO (optional):
1. Add support for search collection

**PS 3**: INTENDED:
1. Reviews are not rewritten, as I plan to move them into separate endpoint and request with pagination by product.

### CODE REVIEW

**Comment by alfredsgenkins** [comment]
Ha-ha, very funny.

Please describe exact issue. At what moment we had a PHP coding style defined? How can I follow a thing which does not exist as I am aware?

PHPStorm does not throw any issues / major warnings.

This is also WIP, I will request you as a review and specify dependencies when ready to CR.

**Comment by eli-l** [comment]
https://devdocs.magento.com/guides/v2.3/coding-standards/code-standard-php.html

**Comment by alfredsgenkins** [comment]
Thanks, I will take a look. This is first time someone mentions this to me :)

**Comment by eli-l** [comment]
Pathetic

Ilja Lapkovskis
On 25 Oct 2019, 00:23 +0300, Alfreds Genkins <notifications@github.com>, wrote:
> Thanks, I will take a look. This is first time someone mentions this to me :)
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
 
<https://beacon.by/scandiweb/progressive-web-apps-future-of-mobile-ecommerce>

**Pull request closed without merging**
