### PR TITLE
product graphql issue fix

### PR DESCRIPTION
**Pull request by sandy6666**

### CODE REVIEW

**Comment by sandy6666** [comment]
https://github.com/scandipwa/scandipwa/issues/3042

**Comment by sandy6666** [comment]
@zans-laksa please review

**Comment by zans-laksa** [comment]
I believe we don't support php 7.3, and don't fix issues when the code has unsupported syntax in elder php versions.
Thus errors like this will likely occur in a future.

**Comment by carinadues** [comment]
The issue was closed.

**Pull request closed without merging**
